# A list of Warp UI token configs and other options for the WarpCore
# Configs can be defined here, in tokens.json, or in tokens.ts
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  - chainName: ethereum
    standard: EvmHypCollateral
    decimals: 18
    symbol: WWBTC
    name: Wrapped Wrapped Bitcoin
    addressOrDenom: "0x8c95540FB7eeBa511a3dceAF405329f87B6d22FA"
    collateralAddressOrDenom: "0x0000000000004250039d1cf730bdd00b31942d18"
    connections:
      - { token: ethereum|sepolia|0x1b1aa1de252145a6a73a5e73cda64c34260891eb }
  - chainName: sepolia
    standard: EvmHypSynthetic
    decimals: 18
    symbol: WWBTCS
    name: WWBTCS
    addressOrDenom: "0x1b1aa1de252145a6a73a5e73cda64c34260891eb"
    connections:
      - { token: ethereum|ethereum|0x8c95540FB7eeBa511a3dceAF405329f87B6d22FA }




